apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-sample
  labels:
    app: synergy-chandan
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: synergy-chandan
  template:
    metadata:
      labels:
        app: synergy-chandan
    spec:
      containers:
      - name: synergy-chandan
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}