apiVersion: v1
kind: Service
metadata:
  name: python-sample-service
spec:
  type: {{ .Values.service.type}}
  selector:
    app: synergy-chandan
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
